# app:
    # resource: '@AppBundle/Controller/'
    # resource: 'AppBundle/Controller/DefaultController.php'
    # type: annotation

places: # [FOS-REST]
    type: rest
    resource: AppBundle\Controller\PlaceController

users:
    type: rest
    resource: AppBundle\Controller\UserController